# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: YuanJunwen's Home
email: yjw6174@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Always bear in mind that your own resolution to success is ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yuanjunwen.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  yjw6174

# Build settings
markdown: kramdown
#kramdown
